CREATE TABLE drones (
  id SERIAL PRIMARY KEY,
  model TEXT NOT NULL,
  capacity INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
